### PR TITLE
Update Thai localization

### PR DESCRIPTION
**Pull request by altinat**

### CODE REVIEW

**Comment by rinme** [comment]
I was done about [**this**](https://github.com/nullxception/boorusphere/pull/69) already

**Comment by nullxception** [comment]
hmm something is conflicted with previous PR #69.
should we use this or just update `rating.questionable` ?
I don't speak thai so I'm not sure.

**Comment by rinme** [comment]
> hmm something is conflicted with previous PR #69. should we use this or just update `rating.questionable` ? I don't speak thai so I'm not sure.

For that I will change from my commit instead, It's sounds good and should be change.

Updated: I just [pull](https://github.com/nullxception/boorusphere/pull/72) for the new commit. You may close this one and push from mine instead.

**Comment by nullxception** [comment]
> > hmm something is conflicted with previous PR #69. should we use this or just update `rating.questionable` ? I don't speak thai so I'm not sure.
> 
> For that I will change from my commit instead, It's sounds good and should be change.
> 
> Updated: I just [pull](https://github.com/nullxception/boorusphere/pull/72) for the new commit. You may close this one and push from mine instead.

awesome, thank you!

**Pull request closed without merging**
