### PR TITLE
UwU wanguage a-a-added fow funny puwpose

### PR DESCRIPTION
**Pull request by rinme**
# What's n-nyew?!!
+ UwU wanguage fow funny puwpose (even it's nyot that funny) ÚwÚ
I think i-it w-wouwd be funny t-to have a (nyot t-that) funny wanguage muhahahahahaha

_Pwease don't waugh at me meo `*cries*`_
_Nyow I d-d-doing with onye commit muhahahahahaha_
_RIP autocorrect_

### CODE REVIEW

**Comment by nullxception** [comment]
I tried using this language but apparently it breaks the app 😭.
There's a way to technically "adding alien language" but apparently it's a tedious work on flutter.

**Comment by rinme** [comment]
> I tried using this language but apparently it breaks the app 😭.
> Technically, there's a way to add "alien language" but apparently it's a tedious work on flutter.

What a bad luck 😭😭😭😭

**Comment by Tienisto** [comment]
The relevant line should be https://github.com/nullxception/boorusphere/blob/46eaaa6f0a46da8ef7e1aa20d02da7659354a6de/lib/presentation/boorusphere.dart#L71

The slang i18n does not know what locales are real.

Basically, you can use `uwu` in slang but you need to tell Flutter that `en` is active.

```dart
// Convert slang locale to flutter locale
extension on AppLocale {
  Locale get digestedFlutterLocale {
    if (this == AppLocale.uwu) {
      return AppLocale.en.flutterLocale;
    }
    
    // Return the actual locale
    return flutterLocale;
  }
}
```

```
// MaterialApp
locale: TranslationProvider.of(context).locale.digestedFlutterLocale,
```

Just my two cents if you still want the "uwu" language :joy:

**Comment by rinme** [comment]
> The relevant line should be https://github.com/nullxception/boorusphere/blob/46eaaa6f0a46da8ef7e1aa20d02da7659354a6de/lib/presentation/boorusphere.dart#L71
> 
> The slang i18n does not know what locales are real.
> 
> Basically, you can use `uwu` in slang but you need to tell Flutter that `en` is active.
> 
> ```dart
> // Convert slang locale to flutter locale
> extension on AppLocale {
>   Locale get digestedFlutterLocale {
>     if (this == AppLocale.uwu) {
>       return AppLocale.en.flutterLocale;
>     }
>     
>     // Return the actual locale
>     return flutterLocale;
>   }
> }
> ```
> 
> ```
> // MaterialApp
> locale: TranslationProvider.of(context).locale.digestedFlutterLocale,
> ```
> 
> Just my two cents if you still want the "uwu" language :joy:

Would be good, if it wouldn't break others things. Did you tried yet?

In case you do then try fire pr 😀.

I would commit newer version of locales soon.

**Pull request merged**
